site_name: Law Codes
site_description: "Compilation of the Kaharagian legal code in Markdown, published as documentation."
site_url: "https://<org>.github.io/lawcodes"
docs_dir: lawcodes/
theme:
  name: readthedocs
  navigation_depth: 4
  collapse_navigation: true
  highlightjs: true
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search
